web:
    image: richarvey/nginx-php-fpm
    volumes:
        - ./:/global
        - ./provision/start.sh:/start.sh

    ports: 
        - "8080:80"
    links:
        - cache
        - redis

cache:
    image: memcached
    ports:
        - "11211:11211"

redis:
    image: redis
    ports: 
        - "6379:6379"
    volumes:
        - ./:/global
        - ./provision/redis-entrypoint.sh:/entrypoint.sh
