web:
    image: richarvey/nginx-php-fpm
    volumes:
        - ./:/global
        - ./start.sh:/start.sh

    ports: 
        - "8080:80"
    links:
        - cache

cache:
    image: memcached
    ports:
        - "11211:11211"
